### ISSUE TITLE
Linkable sections in terms

### ISSUE THREAD

**Issue by msherry** [balanced/www.balancedpayments.com#261]
I'd like to see the terms pages, particularly the [Seller Agreement](https://www.balancedpayments.com/terms/selleragreement) page, have linkable subsections. Right now when e.g. referring people to the 'Prohibited Transactions' section I have to send a link to the page, then tell them to scroll down to section 9. We can do better than this.

**Comment by mjallday** [comment]
This should be an easy fix. The issue is that the document is incorrectly marked up. it uses bold (`**title**`) to emphasize sections when it should be using headings (`### title`).

The [Acceptable Use](https://github.com/balanced/www.balancedpayments.com/blob/master/contents/terms/acceptable_use.md) document is correctly marked up as evidenced by clicking through to this section - https://www.balancedpayments.com/terms/acceptable_use#prohibited-items-and-activities
